---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helm-provisioner
  name: helm-provisioner
  namespace: openshift-rukpak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-provisioner
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app: helm-provisioner
    spec:
      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=1
            - --client-ca-file=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - --tls-cert-file=/etc/pki/tls/tls.crt
            - --tls-private-key-file=/etc/pki/tls/tls.key
            - --upstream-ca-file=/etc/configmaps/ca-bundle/service-ca.crt
          image: ${KUBE_RBAC_PROXY_IMAGE}
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          resources:
            requests:
              cpu: 1m
              memory: 15Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /etc/pki/tls
              name: certs
            - mountPath: /etc/configmaps/ca-bundle
              name: ca-bundle
              readOnly: false
        - args:
            - --unpack-image=${RUKPAK_IMAGE}
            - --base-upload-manager-url=https://core.openshift-rukpak.svc
            - --storage-dir=/var/cache/bundles
            - --http-bind-address=127.0.0.1:8080
            - --http-external-address=https://helm-provisioner.openshift-rukpak.svc
            - --bundle-ca-file=/etc/configmaps/ca-bundle/service-ca.crt
          command:
            - /helm
          image: ${RUKPAK_IMAGE}
          imagePullPolicy: IfNotPresent
          name: manager
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 160Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /var/cache/bundles
              name: bundle-cache
            - mountPath: /etc/pki/tls
              name: certs
            - mountPath: /etc/configmaps/ca-bundle
              name: ca-bundle
              readOnly: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: helm-provisioner-admin
      volumes:
        - emptyDir: {}
          name: bundle-cache
        - name: certs
          secret:
            optional: false
            secretName: helm-provisioner-cert
        - configMap:
            items:
              - key: service-ca.crt
                path: service-ca.crt
            name: openshift-service-ca.crt
          name: ca-bundle
