---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  name: rukpak-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: rukpak-webhook-service
        namespace: openshift-rukpak
        path: /validate-core-v1-configmap
    failurePolicy: Fail
    name: vconfigmaps.core.rukpak.io
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: rukpak-system
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - DELETE
        resources:
          - configmaps
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: rukpak-webhook-service
        namespace: openshift-rukpak
        path: /validate-core-rukpak-io-v1alpha1-bundle
    failurePolicy: Fail
    name: vbundles.core.rukpak.io
    rules:
      - apiGroups:
          - core.rukpak.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - bundles
    sideEffects: None
